set(FUtils_SRC
    FUtils/FUAssert.cpp
	FUtils/FUBase64.cpp
	FUtils/FUBoundingBox.cpp
	FUtils/FUBoundingSphere.cpp
	FUtils/FUBoundingTest.cpp
	FUtils/FUCrc32.cpp
	FUtils/FUCrc32Test.cpp
	FUtils/FUCriticalSection.cpp
	FUtils/FUDaeEnum.cpp
	FUtils/FUDateTime.cpp
	FUtils/FUDebug.cpp
	FUtils/FUError.cpp
	FUtils/FUErrorLog.cpp
	FUtils/FUEventTest.cpp
	FUtils/FUFile.cpp
	FUtils/FUFileManager.cpp
	FUtils/FUFileManagerTest.cpp
	FUtils/FUFunctorTest.cpp
	FUtils/FULogFile.cpp
	FUtils/FUObject.cpp
	FUtils/FUObjectTest.cpp
	FUtils/FUObjectType.cpp
	FUtils/FUParameter.cpp
	FUtils/FUParameterizable.cpp
	FUtils/FUPluginManager.cpp
	FUtils/FUSemaphore.cpp
	FUtils/FUStringBuilder.cpp
	FUtils/FUStringBuilderTest.cpp
	FUtils/FUStringConversion.cpp
	FUtils/FUStringConversionTest.cpp
	FUtils/FUStringTest.cpp
	FUtils/FUSynchronizableObject.cpp
	FUtils/FUTestBed.cpp
	FUtils/FUThread.cpp
	FUtils/FUTracker.cpp
	FUtils/FUUniqueStringMap.cpp
	FUtils/FUUniqueStringMapTest.cpp
	FUtils/FUUri.cpp
	FUtils/FUXmlDocument.cpp
	FUtils/FUXmlParser.cpp
	FUtils/FUXmlWriter.cpp
	FUtils/StdAfx.cpp
)

set(FUtils_H
    FUtils/FUAssert.h
	FUtils/FUBase64.h
	FUtils/FUBoundingBox.h
	FUtils/FUBoundingSphere.h
	FUtils/FUCrc32.h
	FUtils/FUCriticalSection.h
	FUtils/FUDaeEnum.h
	FUtils/FUDaeEnumSyntax.h
	FUtils/FUDaeSyntax.h
	FUtils/FUDateTime.h
	FUtils/FUDebug.h
	FUtils/FUError.h
	FUtils/FUErrorLog.h
	FUtils/FUEvent.h
	FUtils/FUFile.h
	FUtils/FUFileManager.h
	FUtils/FUFunctor.h
	FUtils/FULogFile.h
	FUtils/FUObject.h
	FUtils/FUObjectType.h
	FUtils/FUParameter.h
	FUtils/FUParameterizable.h
	FUtils/FUPlugin.h
	FUtils/FUPluginManager.h
	FUtils/FUSemaphore.h
	FUtils/FUSingleton.h
	FUtils/FUString.h
	FUtils/FUStringBuilder.h
	FUtils/FUStringConversion.h
	FUtils/FUSynchronizableObject.h
	FUtils/FUTestBed.h
	FUtils/FUThread.h
	FUtils/FUtils.h
	FUtils/FUTracker.h
	FUtils/FUUniqueStringMap.h
	FUtils/FUUri.h
	FUtils/FUXmlDocument.h
	FUtils/FUXmlParser.h
	FUtils/FUXmlWriter.h
	FUtils/Platforms.h
	FUtils/StdAfx.h
)
