set(FCDocument_SRC
    FCDocument/FCDAnimated.cpp
	FCDocument/FCDAnimation.cpp
	FCDocument/FCDAnimationChannel.cpp
	FCDocument/FCDAnimationClip.cpp
	FCDocument/FCDAnimationClipTools.cpp
	FCDocument/FCDAnimationCurve.cpp
	FCDocument/FCDAnimationCurveTools.cpp
	FCDocument/FCDAnimationKey.cpp
	FCDocument/FCDAnimationMultiCurve.cpp
	FCDocument/FCDAsset.cpp
	FCDocument/FCDCamera.cpp
	FCDocument/FCDController.cpp
	FCDocument/FCDControllerInstance.cpp
	FCDocument/FCDControllerTools.cpp
	FCDocument/FCDEffect.cpp
	FCDocument/FCDEffectCode.cpp
	FCDocument/FCDEffectParameter.cpp
	FCDocument/FCDEffectParameterFactory.cpp
	FCDocument/FCDEffectParameterSampler.cpp
	FCDocument/FCDEffectParameterSurface.cpp
	FCDocument/FCDEffectPass.cpp
	FCDocument/FCDEffectPassShader.cpp
	FCDocument/FCDEffectPassState.cpp
	FCDocument/FCDEffectProfile.cpp
	FCDocument/FCDEffectProfileFX.cpp
	FCDocument/FCDEffectStandard.cpp
	FCDocument/FCDEffectTechnique.cpp
	FCDocument/FCDEffectTools.cpp
	FCDocument/FCDEmitter.cpp
	FCDocument/FCDEmitterInstance.cpp
	FCDocument/FCDEmitterObject.cpp
	FCDocument/FCDEmitterParticle.cpp
	FCDocument/FCDEntity.cpp
	FCDocument/FCDEntityInstance.cpp
	FCDocument/FCDEntityReference.cpp
	FCDocument/FCDExternalReferenceManager.cpp
	FCDocument/FCDExtra.cpp
	FCDocument/FCDForceDeflector.cpp
	FCDocument/FCDForceDrag.cpp
	FCDocument/FCDForceField.cpp
	FCDocument/FCDForceGravity.cpp
	FCDocument/FCDForcePBomb.cpp
	FCDocument/FCDForceWind.cpp
	FCDocument/FCDGeometry.cpp
	FCDocument/FCDGeometryInstance.cpp
	FCDocument/FCDGeometryMesh.cpp
	FCDocument/FCDGeometryNURBSSurface.cpp
	FCDocument/FCDGeometryPolygons.cpp
	FCDocument/FCDGeometryPolygonsInput.cpp
	FCDocument/FCDGeometryPolygonsTools.cpp
	FCDocument/FCDGeometrySource.cpp
	FCDocument/FCDGeometrySpline.cpp
	FCDocument/FCDImage.cpp
	FCDocument/FCDLibrary.cpp
	FCDocument/FCDLight.cpp
	FCDocument/FCDLightTools.cpp
	FCDocument/FCDMaterial.cpp
	FCDocument/FCDMaterialInstance.cpp
	FCDocument/FCDMorphController.cpp
	FCDocument/FCDObject.cpp
	FCDocument/FCDObjectWithId.cpp
	FCDocument/FCDocument.cpp
	FCDocument/FCDocumentTools.cpp
	FCDocument/FCDParameterAnimatable.cpp
	FCDocument/FCDParticleModifier.cpp
	FCDocument/FCDPhysicsAnalyticalGeometry.cpp
	FCDocument/FCDPhysicsForceFieldInstance.cpp
	FCDocument/FCDPhysicsMaterial.cpp
	FCDocument/FCDPhysicsModel.cpp
	FCDocument/FCDPhysicsModelInstance.cpp
	FCDocument/FCDPhysicsRigidBody.cpp
	FCDocument/FCDPhysicsRigidBodyInstance.cpp
	FCDocument/FCDPhysicsRigidBodyParameters.cpp
	FCDocument/FCDPhysicsRigidConstraint.cpp
	FCDocument/FCDPhysicsRigidConstraintInstance.cpp
	FCDocument/FCDPhysicsScene.cpp
	FCDocument/FCDPhysicsShape.cpp
	FCDocument/FCDPlaceHolder.cpp
	FCDocument/FCDSceneNode.cpp
	FCDocument/FCDSceneNodeIterator.cpp
	FCDocument/FCDSceneNodeTools.cpp
	FCDocument/FCDSkinController.cpp
	FCDocument/FCDTargetedEntity.cpp
	FCDocument/FCDTexture.cpp
	FCDocument/FCDTransform.cpp
	FCDocument/FCDVersion.cpp
)

set(base_FCDocument_H
    FCDocument/FCDAnimated.h
	FCDocument/FCDAnimation.h
	FCDocument/FCDAnimationChannel.h
	FCDocument/FCDAnimationClip.h
	FCDocument/FCDAnimationClipTools.h
	FCDocument/FCDAnimationCurve.h
	FCDocument/FCDAnimationCurveTools.h
	FCDocument/FCDAnimationKey.h
	FCDocument/FCDAnimationMultiCurve.h
	FCDocument/FCDAsset.h
	FCDocument/FCDCamera.h
	FCDocument/FCDController.h
	FCDocument/FCDControllerInstance.h
	FCDocument/FCDControllerTools.h
	FCDocument/FCDEffect.h
	FCDocument/FCDEffectCode.h
	FCDocument/FCDEffectParameter.h
	FCDocument/FCDEffectParameterFactory.h
	FCDocument/FCDEffectParameterSampler.h
	FCDocument/FCDEffectParameterSurface.h
	FCDocument/FCDEffectPass.h
	FCDocument/FCDEffectPassShader.h
	FCDocument/FCDEffectPassState.h
	FCDocument/FCDEffectProfile.h
	FCDocument/FCDEffectProfileFX.h
	FCDocument/FCDEffectStandard.h
	FCDocument/FCDEffectTechnique.h
	FCDocument/FCDEffectTools.h
	FCDocument/FCDEmitter.h
	FCDocument/FCDEmitterInstance.h
	FCDocument/FCDEmitterObject.h
	FCDocument/FCDEmitterParticle.h
	FCDocument/FCDEntity.h
	FCDocument/FCDEntityInstance.h
	FCDocument/FCDEntityReference.h
	FCDocument/FCDExternalReferenceManager.h
	FCDocument/FCDExtra.h
	FCDocument/FCDForceDeflector.h
	FCDocument/FCDForceDrag.h
	FCDocument/FCDForceField.h
	FCDocument/FCDForceGravity.h
	FCDocument/FCDForcePBomb.h
	FCDocument/FCDForceTyped.h
	FCDocument/FCDForceWind.h
	FCDocument/FCDGeometry.h
	FCDocument/FCDGeometryInstance.h
	FCDocument/FCDGeometryMesh.h
	FCDocument/FCDGeometryNURBSSurface.h
	FCDocument/FCDGeometryPolygons.h
	FCDocument/FCDGeometryPolygonsInput.h
	FCDocument/FCDGeometryPolygonsTools.h
	FCDocument/FCDGeometrySource.h
	FCDocument/FCDGeometrySpline.h
	FCDocument/FCDImage.h
	FCDocument/FCDLibrary.h
	FCDocument/FCDLight.h
	FCDocument/FCDLightTools.h
	FCDocument/FCDMaterial.h
	FCDocument/FCDMaterialInstance.h
	FCDocument/FCDMorphController.h
	FCDocument/FCDObject.h
	FCDocument/FCDObjectWithId.h
	FCDocument/FCDocument.h
	FCDocument/FCDocumentTools.h
	FCDocument/FCDParameterAnimatable.h
	FCDocument/FCDParticleEmitter.h
	FCDocument/FCDParticleModifier.h
	FCDocument/FCDPhysicsAnalyticalGeometry.h
	FCDocument/FCDPhysicsForceFieldInstance.h
	FCDocument/FCDPhysicsMaterial.h
	FCDocument/FCDPhysicsModel.h
	FCDocument/FCDPhysicsModelInstance.h
	FCDocument/FCDPhysicsRigidBody.h
	FCDocument/FCDPhysicsRigidBodyInstance.h
	FCDocument/FCDPhysicsRigidBodyParameters.h
	FCDocument/FCDPhysicsRigidConstraint.h
	FCDocument/FCDPhysicsRigidConstraintInstance.h
	FCDocument/FCDPhysicsScene.h
	FCDocument/FCDPhysicsShape.h
	FCDocument/FCDPlaceHolder.h
	FCDocument/FCDSceneNode.h
	FCDocument/FCDSceneNodeIterator.h
	FCDocument/FCDSceneNodeTools.h
	FCDocument/FCDSkinController.h
	FCDocument/FCDTargetedEntity.h
	FCDocument/FCDTexture.h
	FCDocument/FCDTransform.h
	FCDocument/FCDVersion.h
)
